{% set name = "GOUDA" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/GOUDA-{{ version }}.tar.gz
  sha256: cf36ed6492a6128d280ae18931ff079b12af8eb13c5e1eec5f66d27da7d77c6e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - colorama
    - matplotlib-base
    - numpy
    - python >=3.6

test:
  imports:
    - gouda
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Mullans/GOUDA/
  summary: Good Old Utilities for Data Analysis!
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Mullans
