{% set name = "gouda" %}
{% set version = "0.5.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/GOUDA-{{ version }}.tar.gz
  sha256: 09c627c8662c856ec0eac343256e57a5c2d3ff3c18be7885ffb2d7e7b85dd5d5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pyscaffold >=3.2a0,<3.3a0
    - python >=3.6
  run:
    - importlib-metadata
    - colorama
    - matplotlib-base
    - numpy
    - python >=3.6

test:
  imports:
    - gouda
  commands:
    - pip check
    - putup --help
  requires:
    - pip

about:
  home: https://github.com/mullans/GOUDA
  summary: Good Old Utilities for Data Analysis!
  dev_url: https://github.com/mullans/GOUDA
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Mullans
